<?php
/**
 * @file
 * Billing client module.
 *
 */

/**
 * Implements hook_menu().
 */
function billing_client_menu() {
  $items = array();

  $items['admin/config/system/billing_client'] = array(
    'title' => 'Billing Client settings',
    'description' => 'Configure Billing API integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('billing_client_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'billing_client.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/system/billing_client/settings'] = array(
    'title' => 'Billing Client settings',
    'description' => 'Configure Billing API integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('billing_client_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'billing_client.admin.inc',

    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/system/billing_client/users'] = array(
    'title' => 'Billing Client Users',
    'description' => 'Synchronize selected users.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('billing_client_users'),
    'access arguments' => array('administer site configuration'),
    'file' => 'billing_client.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}


/**
 * Implements hook_user_login().
 */
function billing_client_user_login(&$edit, $account) {
  $session_key = billing_client_get('user/:name', 
    array(
      ':name' => $account->name,
    ));
  drupal_set_message('<pre>' . print_r($session_key,true) . '</pre>');
}




/**
 * Implements hook_user_insert().
 */
function billing_client_user_insert(&$edit, $account, $category) {
  $request['name'] = $account->name;
  $request['email'] = $account->mail;
  $request['status'] = $account->status;
  billing_client_post('user', $request);
}

/**
 * Implements hook_user_update().
 */
function billing_client_user_update(&$edit, $account, $category) {
  $request[':name'] = $account->original->name;
  $request['name'] = $account->name;
  $request['email'] = $account->mail;
  $request['status'] = $account->status;
  billing_client_put('user/:name', $request);

}

/**
 * Implements hook_user_delete().
 */
function billing_client_user_delete($account) {
  $request[':name'] = $account->name;
  billing_client_delete('user/:name', $request);
}


/**
 * Send GET request.
 */
function billing_client_get($url, $params = array()) {

  billing_client_prepareCommand($url, $params);
  $options = array(
    'method' => 'GET',
    'headers' => array(
      'Content-Type' => 'application/json',
      'Accept' => '*/*',
      'User-Agent' => 'Billing Client module for Drupal',
      'Token' => variable_get('billing_client_token'),
    )
  );
  $url = variable_get('billing_client_api_url') . '/' . $url;
  $answer = drupal_http_request($url, $options);
  if($answer->code == '200'){
    if(!empty($answer->data)){
      return json_decode($answer->data, TRUE);
    }
    return $answer->status_message;
  }
  else{
    if(isset($answer->error)){
      return $answer->error;
    }
    return FALSE;
  }
}

/**
 * Send DELETE request.
 */
function billing_client_delete($url, $params = array()) {

  billing_client_prepareCommand($url, $params);
  $options = array(
    'method' => 'DELETE',
    'headers' => array(
      'Content-Type' => 'application/json',
      'Accept' => '*/*',
      'User-Agent' => 'Billing Client module for Drupal',
      'Token' => variable_get('billing_client_token'),
    )
  );
  $url = variable_get('billing_client_api_url') . '/' . $url;
  $answer = drupal_http_request($url, $options);
  if($answer->code == '200'){
    if(!empty($answer->data)){
      return json_decode($answer->data, TRUE);
    }
    return $answer->status_message;
  }
  else{
    if(isset($answer->error)){
      return $answer->error;
    }
    return FALSE;
  }
}

/**
 * Send POST request.
 */
function billing_client_post($url, $params = array()) {

  billing_client_prepareCommand($url, $params);
  $options = array(
    'method' => 'POST',
    'headers' => array(
      'Content-Type' => 'application/json',
      'Accept' => '*/*',
      'User-Agent' => 'Billing Client module for Drupal',
      'Token' => variable_get('billing_client_token'),
    ),
    'data' => json_encode($params),
  );
  $url = variable_get('billing_client_api_url') . '/' . $url;
  $answer = drupal_http_request($url, $options);
  if($answer->code == '200'){
    if(!empty($answer->data)){
      return json_decode($answer->data, TRUE);
    }
    return $answer->status_message;
  }
  else{
    if(isset($answer->error)){
      return $answer->error;
    }
    return FALSE;
  }
}

/**
 * Send PUT request.
 */
function billing_client_put($url, $params = array()) {

  billing_client_prepareCommand($url, $params);
  $options = array(
    'method' => 'PUT',
    'headers' => array(
      'Content-Type' => 'application/json',
      'Accept' => '*/*',
      'User-Agent' => 'Billing Client module for Drupal',
      'Token' => variable_get('billing_client_token'),
    ),
    'data' => json_encode($params),
  );
  $url = variable_get('billing_client_api_url') . '/' . $url;
  $answer = drupal_http_request($url, $options);
  if($answer->code == '200'){
    if(!empty($answer->data)){
      return json_decode($answer->data, TRUE);
    }
    return $answer->status_message;
  }
  else{
    if(isset($answer->error)){
      return $answer->error;
    }
    return FALSE;
  }
}

/**
 * Replace all :name in $url with data from $params.
 */
function billing_client_prepareCommand(&$command, &$params) {
  foreach($params as $key => $val){
    if($key[0] == ':'){
      $command = str_replace($key, $val, $command);
      unset($params[$key]);
    }
  }
}
